# fly.toml app configuration file generated for snow-day-predictor-website on 2024-02-02T11:44:21-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snow-day-predictor-website'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
